### ISSUE TITLE
Composter TESR IllegalArgumentException

### ISSUE THREAD

**Issue by elifoster** [squeek502/VeganOption#75]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  literalascension (literalascension-1.10.2-1.0.1.1.jar)
  FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  ForgelinPlugin (Forgelin-1.4.0.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  ASMPlugin (VeganOption-mc1.10.2-devbuild1.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 3/10/17 1:18 AM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at squeek.veganoption.blocks.renderers.RenderComposter.renderTileEntityAt(RenderComposter.java:49)
	at squeek.veganoption.blocks.renderers.RenderComposter.func_180535_a(RenderComposter.java:17)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at squeek.veganoption.blocks.renderers.RenderComposter.renderTileEntityAt(RenderComposter.java:49)
	at squeek.veganoption.blocks.renderers.RenderComposter.func_180535_a(RenderComposter.java:17)

-- Block Entity Details --
Details:
	Name: VeganOption.composter // squeek.veganoption.blocks.tiles.TileEntityComposter
	Block type: ID #674 (tile.VeganOption.composter // squeek.veganoption.blocks.BlockComposter)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-1722,64,-121), Chunk: (at 6,4,7 in -108,-8; contains blocks -1728,0,-128 to -1713,255,-113), Region: (-4,-1; contains chunks -128,-32 to -97,-1, blocks -2048,0,-512 to -1537,255,-1)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['SatanicSanta'/670, l='MpServer', x=-1661.79, y=64.00, z=-97.95]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (248,64,128), Chunk: (at 8,4,0 in 15,8; contains blocks 240,0,128 to 255,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 453385 game time, 59232 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 33 total; [EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1699.62, y=63.00, z=-99.47], EntityItem['item.item.dyePowder.black'/10240, l='MpServer', x=-1597.38, y=61.00, z=-99.86], EntityCreeper['Creeper'/12294, l='MpServer', x=-1683.50, y=39.00, z=-70.50], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1686.09, y=63.94, z=-117.34], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1686.14, y=63.94, z=-116.56], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1720.82, y=63.00, z=-98.92], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1723.11, y=68.00, z=-96.40], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1663.12, y=64.00, z=-93.48], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1721.41, y=64.00, z=-118.99], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1657.34, y=61.00, z=-93.26], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1688.74, y=63.94, z=-111.25], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1663.34, y=64.00, z=-96.94], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1721.11, y=63.00, z=-99.16], EntityBat['Bat'/12089, l='MpServer', x=-1647.99, y=26.20, z=-126.57], EntityZombie['Zombie'/12090, l='MpServer', x=-1629.52, y=36.00, z=-123.34], EntitySquid['Squid'/11969, l='MpServer', x=-1661.82, y=53.00, z=-117.14], EntitySquid['Squid'/11970, l='MpServer', x=-1661.37, y=53.60, z=-118.85], EntitySquid['Squid'/11971, l='MpServer', x=-1661.14, y=53.04, z=-118.40], EntityZombie['Zombie'/12108, l='MpServer', x=-1629.45, y=36.00, z=-124.04], EntityZombie['Zombie'/12109, l='MpServer', x=-1631.29, y=36.00, z=-123.47], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1685.80, y=63.94, z=-115.70], EntityBat['Bat'/10959, l='MpServer', x=-1672.36, y=24.96, z=-114.36], EntitySheep['Sheep'/12111, l='MpServer', x=-1630.38, y=64.00, z=-122.82], EntityCreeper['Creeper'/11984, l='MpServer', x=-1655.50, y=18.00, z=-75.50], EntityBat['Bat'/11985, l='MpServer', x=-1662.83, y=18.04, z=-79.75], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1688.25, y=63.94, z=-115.26], EntitySpider['Spider'/12385, l='MpServer', x=-1663.50, y=34.00, z=-75.50], EntityCreeper['Creeper'/11622, l='MpServer', x=-1672.50, y=43.00, z=-112.16], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1722.46, y=64.00, z=-118.64], EntityZombie['Zombie'/12275, l='MpServer', x=-1674.50, y=14.00, z=-89.50], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1722.02, y=64.00, z=-99.72], EntityOtherPlayerMP['kingluke_'/175, l='MpServer', x=-1723.11, y=68.00, z=-96.40], EntityPlayerSP['SatanicSanta'/670, l='MpServer', x=-1661.79, y=64.00, z=-97.95]]
	Retry entities: 25 total; [EntityItem['item.item.dyePowder.black'/10240, l='MpServer', x=-1597.38, y=61.00, z=-99.86], EntitySquid['Squid'/9740, l='MpServer', x=-1596.19, y=61.10, z=-108.73], EntityBat['Bat'/9806, l='MpServer', x=-1540.39, y=44.10, z=-73.24], EntityItem['item.item.rottenFlesh'/9807, l='MpServer', x=-1540.56, y=64.00, z=-84.38], EntityCreeper['Creeper'/9808, l='MpServer', x=-1553.45, y=64.00, z=-97.21], EntityCreeper['Creeper'/10004, l='MpServer', x=-1566.50, y=38.00, z=-130.50], EntityCreeper['Creeper'/10005, l='MpServer', x=-1567.98, y=38.00, z=-130.46], EntitySkeleton['Skeleton'/9750, l='MpServer', x=-1584.10, y=51.00, z=-87.51], EntitySkeleton['Skeleton'/9751, l='MpServer', x=-1577.42, y=50.00, z=-88.57], EntityCreeper['Creeper'/9752, l='MpServer', x=-1582.22, y=51.00, z=-89.52], EntityBat['Bat'/9689, l='MpServer', x=-1597.28, y=24.52, z=-128.24], EntityCreeper['Creeper'/9753, l='MpServer', x=-1578.76, y=50.00, z=-89.65], EntityItem['item.tile.dirt.default'/9696, l='MpServer', x=-1595.34, y=60.00, z=-100.34], EntityItem['item.tile.dirt.default'/9697, l='MpServer', x=-1596.59, y=60.00, z=-98.66], EntityItem['item.tile.dirt.default'/9698, l='MpServer', x=-1597.32, y=60.00, z=-100.13], EntitySquid['Squid'/9699, l='MpServer', x=-1586.25, y=62.55, z=-115.60], EntitySquid['Squid'/9700, l='MpServer', x=-1584.01, y=62.16, z=-102.44], EntityCreeper['Creeper'/10021, l='MpServer', x=-1584.50, y=43.00, z=-130.50], EntitySquid['Squid'/9702, l='MpServer', x=-1597.60, y=61.11, z=-111.60], EntityCreeper['Creeper'/9766, l='MpServer', x=-1562.61, y=70.00, z=-128.06], EntitySquid['Squid'/9703, l='MpServer', x=-1593.40, y=62.21, z=-128.12], EntitySquid['Squid'/9704, l='MpServer', x=-1589.37, y=62.09, z=-128.00], EntitySpider['Spider'/9768, l='MpServer', x=-1571.88, y=53.10, z=-88.70], EntitySpider['Spider'/9769, l='MpServer', x=-1561.84, y=55.10, z=-89.30], EntityZombie['Zombie'/9770, l='MpServer', x=-1550.59, y=50.00, z=-86.51]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.12.3
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 264964544 bytes (252 MB) / 1044381696 bytes (996 MB) up to 1044381696 bytes (996 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2239 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2239-universal.jar) 
	UCHIJAAAAAA	Forge{12.18.3.2239} [Minecraft Forge] (forge-1.10.2-12.18.3.2239-universal.jar) 
	UCHIJAAAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJAAAAAA	JEI{3.14.7.415} [Just Enough Items] (jei_1.10.2-3.14.7.415.jar) 
	UCHIJAAAAAA	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJAAAAAA	blockrenderer{1.0.0} [BlockRenderer] (BlockRenderer-1.0.0.jar) 
	UCHIJAAAAAA	ceramics{1.10.2-1.1.4b} [Ceramics] (Ceramics-1.10.2-1.1.4b.jar) 
	UCHIJAAAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAAAA	chisel{MC1.10.2-0.0.8.12} [Chisel] (Chisel-MC1.10.2-0.0.8.12.jar) 
	UCHIJAAAAAA	CodeChickenLib{2.5.6.233} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJAAAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCHIJAAAAAA	MineTweaker3{3.0.20} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCHIJAAAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.20.jar) 
	UCHIJAAAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJAAAAAA	farseek{2.1} [Farseek] (Farseek-1.9.4-2.1.jar) 
	UCHIJAAAAAA	forgelin{1.4.0} [Forgelin] (Forgelin-1.4.0.jar) 
	UCHIJAAAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.10.2.jar) 
	UCHIJAAAAAA	literalascension{1.10.2-1.0.1.1} [Literal Ascension] (literalascension-1.10.2-1.0.1.1.jar) 
	UCHIJAAAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAAAA	natura{1.10.2-4.1.0.24} [Natura] (natura-1.10.2-4.1.0.24.jar) 
	UCHIJAAAAAA	ninetaillib{0.0.43} [NineTailLib] (NineTailLib-[1.10.2]-0.0.43-universal.jar) 
	UCHIJAAAAAA	yurtmod{7.01} [Nomadic Tents] (NomadicTents[1.10.2]-7.01.jar) 
	UCHIJAAAAAA	oredictdumper{3.1.3} [OreDictDumper] (OreDictDumper-1.9-3.1.3.jar) 
	UCHIJAAAAAA	oredicttips{1.0.0} [OreDictTips] (OreDictTips-1.10.2-1.0.0.jar) 
	UCHIJAAAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJAAAAAA	reliquia{0.0.7} [Reliquia] (Reliquia-[1.10.2]-0.0.7.jar) 
	UCHIJAAAAAA	StorageDrawers{1.10.2-3.6.1} [Storage Drawers] (StorageDrawers-1.10.2-3.6.1.jar) 
	UCHIJAAAAAA	streams{0.3} [Streams] (Streams-1.9.4-0.3.jar) 
	UCHIJAAAAAA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJAAAAAA	theoneprobe{1.4.4} [The One Probe] (theoneprobe-1.1x-1.4.4.jar) 
	UCHIJAAAAAA	XaeroMinimap{1.12.3} [Xaero's Minimap] (Xaeros_Minimap_1.12.3_Forge_1.10.2.jar) 
	UCHIJAAAAAA	XaeroWorldMap{1.8} [Xaero's World Map] (XaerosWorldMap_b1.8_Forge_1.10.2.jar) 
	UCHIJAAAAAA	VeganOption{unspecified} [The Vegan Option] (VeganOption-mc1.10.2-devbuild1.jar) 
	Loaded coremods (and transformers): 
literalascension (literalascension-1.10.2-1.0.1.1.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  farseek.core.FarseekClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  team.chisel.common.asm.ChiselTransformer
ForgelinPlugin (Forgelin-1.4.0.jar)
  
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
ASMPlugin (VeganOption-mc1.10.2-devbuild1.jar)
  squeek.veganoption.asm.ClassTransformer
llibrary (llibrary-1.7.4-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GT 330M OpenGL Engine GL version 2.1 NVIDIA-10.2.12 310.90.10.05b20, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7 CPU M 620 @ 2.67GHz
```

Probably caused by the whole tile-entities-can-exist-without-its-according-block thing. Got a similar issue in Esteemed Innovation, albeit not with the TESR. Basically, we have to check that the block in the TE's position is actually the correct block before we can access the blockstates*.

*Lex suggested putting the blockstate values the TE needs in the NBT as well as the metadata, but uh, that's a fucking terrible solution 🤣

**Comment by elifoster** [comment]
Just checked, the Composter TESR is the only one with this issue. The Composter TE, and TEs and TESRs for the ender rift and basin do not have this problem.
